### ISSUE TITLE
HTTPS is not working

### ISSUE THREAD

**Issue by theel0ja** [highcharts/github.highcharts.com#5]
HTTPS links in [code.highcharts.com](https://code.highcharts.com/) is not working with HTTPS.

![Unable to connect error message in Firefox](https://cloud.githubusercontent.com/assets/5832930/21286487/0d6b7570-c45e-11e6-8696-74c5e2d3fddf.png)

**Comment by TorsteinHonsi** [comment]
Please note that http://github.highcharts.com is just for testing and should under no circumstances be used in production.

**Comment by jon-a-nygaard** [comment]
Support for SSL on github.highcharts.com was added on February 16.
